import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a4d2e", // Dark forest green
    position: "relative",
  },
  backgroundElements: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    zIndex: 0,
  },
  circle1: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    top: -50,
    right: -50,
  },
  circle2: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    bottom: 100,
    left: -30,
  },
  circle3: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    top: "40%",
    right: 20,
  },
  mushroomContainer1: {
    position: "absolute",
    top: 40,
    left: -120,
    width: 280,
    height: 280,
    opacity: 0.2,
    transform: [{ rotate: "-50deg" }],
  },
  mushroomContainer2: {
    position: "absolute",
    bottom: 40,
    right: -100,
    width: 260,
    height: 260,
    opacity: 0.1,
    transform: [{ rotate: "20deg" }],
  },
  mushroom: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
    tintColor: "rgba(255, 255, 255, 0.7)",
  },
  lettuceContainer: {
    position: "absolute",
    bottom: -130,
    left: -130,
    width: 320,
    height: 320,
    transform: [{ rotate: "-25deg" }],
  },
  lettuce: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  garlicContainer: {
    position: "absolute",
    bottom: -80,
    left: 200,
    width: 280,
    height: 280,
    transform: [{ rotate: "-20deg" }],
  },
  garlic: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  tomatoContainer: {
    position: "absolute",
    bottom: -150,
    right: 80,
    width: 300,
    height: 300,
    transform: [{ rotate: "25deg" }],
  },
  tomato: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  keyboardView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 170,
  },
  logoContainer: {
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  logoFrame: {
    padding: 8,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  logo: {
    width: 160,
    height: 160,
    resizeMode: "contain",
  },
  welcomeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    width: "100%",
    maxWidth: 300,
  },
  welcomeLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    marginHorizontal: 12,
  },
  welcomeText: {
    fontSize: 25,
    fontWeight: "600",
    color: "#fff",
    textAlign: "center",
    letterSpacing: 1.2,
    opacity: 0.95,
  },
  formContainer: {
    width: "100%",
    maxWidth: 380,
  },
  inputContainer: {
    marginBottom: 8,
  },
  inputLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 6,
    paddingLeft: 4,
  },
  inputLabel: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "500",
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 18,
    borderColor: "rgba(255, 255, 255, 0.25)",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 20,
    minHeight: 58,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputIcon: {
    marginRight: 14,
    opacity: 0.8,
  },
  input: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    color: "#fff",
    backgroundColor: "transparent",
    letterSpacing: 0.3,
  },
  eyeIcon: {
    padding: 8,
  },
  forgotPassword: {
    alignSelf: "flex-end",
    marginBottom: 10,
  },
  forgotPasswordText: {
    fontSize: 14,
    color: "#fff",
    opacity: 0.85,
    fontWeight: "500",
  },
  registerPrompt: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 10,
    padding: 12,
    backgroundColor: "rgba(255, 193, 7, 0.2)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 193, 7, 0.5)",
  },
  registerPromptText: {
    fontSize: 14,
    color: "#fff",
    textAlign: "center",
  },
  registerLink: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  primaryButton: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    width: "100%",
    marginTop: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
    overflow: "hidden",
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  primaryButtonText: {
    color: "#1a4d2e",
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: 1,
  },
  buttonArrowContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(26, 77, 46, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    flexWrap: "wrap",
  },
  footerText: {
    fontSize: 14,
    color: "#fff",
    opacity: 0.85,
  },
  footerLink: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "600",
    marginLeft: 4,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
});

